name: Manual workflow

on:
  # workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Configure & build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ninja-multi-vcpkg
        buildPreset: ninja-multi-vcpkg
        packagePreset: ninja-multi-vcpkg

    - name: Tag Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/sbany-*-win64.msi

    - name: Release
      uses: softprops/action-gh-release@v2
      if: false
      with:
        tag_name: "latest"          # Sets a fixed tag name
        name: "Latest Development Build"
        files: build/*-win64.msi
        overwrite_files: true
        prerelease: true            # Optional: Mark as pre-release
      # env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
