name: Vcpkg workflow

on:
  # workflow_dispatch:
  push:
    branches:
      - main  # <--- Added: Saves and binds cache to the main branch scope
    tags:
      - "*.*.*"

jobs:
  build:
    env:
      VCPKG_DEFAULT_TRIPLETL: x64-windows-release
      VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: bootstrap-vcpkg
      run: |
        vcpkg\bootstrap-vcpkg.bat

    # This step assumes `vcpkg` has been bootstrapped (run `./vcpkg/bootstrap-vcpkg`)
    - name: 'Setup NuGet Credentials'
      shell: 'bash'
      # Replace <OWNER> with your organization name
      run: |
        ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/fragrans/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "fragrans" \
          -password "${{ secrets.GITHUB_TOKEN }}"
        ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
         -source "https://nuget.pkg.github.com/fragrans/index.json"

    - name: build
      run: |
        vcpkg\vcpkg.exe install --triplet x64-windows
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows
        cmake --build build --config Release
        cmake --build build --target package
        ls vcpkg
        ls build/vcpkg_installed

    - name: Tag Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/*-win64.msi

    - name: Latest Release
      uses: softprops/action-gh-release@v2
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      with:
        tag_name: "latest"          # Sets a fixed tag name
        name: "Latest Development Build"
        files: build/*-win64.msi
        overwrite_files: true
        prerelease: true            # Optional: Mark as pre-release
      # env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
